// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VzwuOjeTvOLIvv76I-NlWn-mMBoATcM',
    appId: '1:781038682220:web:f2e854dcb47286d01f5849',
    messagingSenderId: '781038682220',
    projectId: 'test-auth-1b62d',
    authDomain: 'test-auth-1b62d.firebaseapp.com',
    storageBucket: 'test-auth-1b62d.firebasestorage.app',
    measurementId: 'G-EBTDH39L63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_qoAq1h2OoAorWP4KlJGgU06WNRpFSU4',
    appId: '1:781038682220:android:cb2f9213586132161f5849',
    messagingSenderId: '781038682220',
    projectId: 'test-auth-1b62d',
    storageBucket: 'test-auth-1b62d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38csTJOImsMEQlT4E_YmDQuQuqh89I_M',
    appId: '1:781038682220:ios:1aa000f6e2e3b91e1f5849',
    messagingSenderId: '781038682220',
    projectId: 'test-auth-1b62d',
    storageBucket: 'test-auth-1b62d.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB38csTJOImsMEQlT4E_YmDQuQuqh89I_M',
    appId: '1:781038682220:ios:1aa000f6e2e3b91e1f5849',
    messagingSenderId: '781038682220',
    projectId: 'test-auth-1b62d',
    storageBucket: 'test-auth-1b62d.firebasestorage.app',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1VzwuOjeTvOLIvv76I-NlWn-mMBoATcM',
    appId: '1:781038682220:web:19c371dd7c803a4e1f5849',
    messagingSenderId: '781038682220',
    projectId: 'test-auth-1b62d',
    authDomain: 'test-auth-1b62d.firebaseapp.com',
    storageBucket: 'test-auth-1b62d.firebasestorage.app',
    measurementId: 'G-P26S3VTHFS',
  );
}
